[package]
name = "hpos-config-gen-cli"
version = "0.0.0"
authors = [
  "Yegor Timoshenko <yegortimoshenko@transumption.com>"
]
edition = "2018"
repository = "https://github.com/Holo-Host/hpos-config"

[dependencies]
docopt = "1.0.2"
failure = "0.1.5"
hpos-config-core = { path = "../core" }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.8.0"
