[package]
name = "hpos-config-gen-cli"
version = "0.1.1"
authors = [
  "Yegor Timoshenko <yegortimoshenko@transumption.com>",
  "zo-el <joelulahanna@gmail.com>"
]
edition = "2018"
repository = "https://github.com/Holo-Host/hpos-config"

[dependencies]
docopt = "1.0.2"
failure = "0.1.5"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
hpos-config-core = { path = "../core" }
rand = "0.6.5"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.8"
