[workspace]

members = [
  "core",
  "derive",
  "generate-cli",
  "generate-web",
  "verify-node"
]

# https://github.com/rust-lang/cargo/issues/5478#issuecomment-518026540
[patch."https://github.com/holochain/holochain-rust".holochain_core_types]
git = "https://github.com/holochain/holochain-rust.git"
branch = "2019-10-13-hydra"
