[package]
name = "holo-config"
version = "0.0.0"
authors = ["perry.kundert@holo.host", "yegortimoshenko@transumption.com"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/Holo-Host/holo-config"

[dependencies]
arrayref = "0.3.5"
base64 = "0.10.1"
docopt = "1.0.2"
ed25519-dalek = { version = "1.0.0-pre.1", features = ["serde"] }
failure = "0.1.5"
getopts = "0.2.19"
lib3h_sodium = "=0.0.10"
rand = "0.6.5"
rust-argon2 = "0.5.1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
sha2 = "0.8.0"
url = "2.1.0"

[dependencies.holochain_conductor_api]
git = "https://github.com/holochain/holochain-rust"
rev = "5b292bd5d81ec20fa7741c2e676b8954e898774e"

[dependencies.holochain_common]
git = "https://github.com/holochain/holochain-rust"
rev = "5b292bd5d81ec20fa7741c2e676b8954e898774e"

[dependencies.holochain_dpki]
git = "https://github.com/holochain/holochain-rust"
rev = "5b292bd5d81ec20fa7741c2e676b8954e898774e"

[[bin]]
name = "holo-config-derive"
path = "src/bin/derive.rs"

[[bin]]
name = "holo-config-generate"
path = "src/bin/generate.rs"
