[package]
name = "holo-config"
version = "0.0.0"
authors = ["perry.kundert@holo.host", "yegortimoshenko@transumption.com"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/Holo-Host/holo-config"

[dependencies]
arrayref = "0.3.5"
base64 = "0.10.1"
bip39 = "=0.6.0-beta.1"
docopt = "1.0.2"
ed25519-dalek = { version = "1.0.0-pre.1", features = ["serde"] }
failure = "0.1.5"
getopts = "0.2.19"
hcid = "0.0.6"
rand = "0.6.5"
rust-argon2 = "0.5.1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
sha2 = "0.8.0"
url = "2.1.0"

[[bin]]
name = "holo-config-derive"
path = "src/bin/derive.rs"

[[bin]]
name = "holo-config-generate"
path = "src/bin/generate.rs"
