[package]
name = "holo-configure"
version = "0.0.0"
authors = ["perry.kundert@holo.host"]
edition = "2018"
description = "HoloPort configuration encoding tools"
keywords = ["holo", "HoloPort"]
categories = ["encoding"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/holo-configuration"
repository = "https://github.com/Holo-Host/holo-configuration"

[dependencies]
getopts = "=0.2.19"
hcid = "=0.0.6"
rust-argon2 = "=0.5.1"
rust-crypto-wasm = "=0.3.1"
ed25519-dalek = "=1.0.0-pre.1"
getrandom = "=0.1.12"
base64 = "=0.10.1"
arrayref = "=0.3.5"
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
