name = "test-quickstart"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"
route = "test-quickstart.holo.host/*"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "quickstart"
route = "quickstart.holo.host/*"

