account_id = "18ff2b4e6205b938652998cfca0d8cff"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"
name = "devnet-quickstart"
route = "devnet-quickstart.holo.host/*"
type = "javascript"

# [build] section is necessary because of a type = "javascript"
# Do not change the type to "webpack" because wrangler is using internally
# webpack v4 which is incompatible with webpack v^5.59 used in this project
[build]
command = "echo 'Deploying build of quickstart from dist directory'"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.mainnet]
name = "quickstart"
route = "quickstart.holo.host/*"
