[package]
name = "hpos-config-into-keystore"
version = "0.0.0"
authors = ["perry.kundert@holo.host", "yegortimoshenko@transumption.com"]
edition = "2018"
repository = "https://github.com/Holo-Host/hpos-config"

[dependencies]
docopt = "1.0.2"
failure = "0.1.5"
hpos-config-core = { path = "../core" }
lazy_static = "1.2"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"

[dependencies.base36]
git = "https://github.com/transumption-unstable/base36"
branch = "2019-12-18-nix"

[dependencies.holochain_conductor_api]
git = "https://github.com/holochain/holochain-rust"
branch = "2019-10-13-hydra"

[dependencies.holochain_common]
git = "https://github.com/holochain/holochain-rust"
branch = "2019-10-13-hydra"

[dependencies.holochain_dpki]
git = "https://github.com/holochain/holochain-rust"
branch = "2019-10-13-hydra"
