[package]
name = "hpos-config-is-valid"
version = "0.0.1"
authors = [
  "Sam Rose <sam.rose@holo.host>"
]
edition = "2018"
repository = "https://github.com/Holo-Host/hpos-config"

[dependencies]
anyhow = "1.0"
hpos-config-core = { path = "../core" }
serde_json = "1.0.64"
