[package]
name = "hpos-config-is-valid"
version = "0.2.0"
authors = [
  "Sam Rose <sam.rose@holo.host>"
]
edition = "2021"
repository = "https://github.com/Holo-Host/hpos-config"

[dependencies]
anyhow = { workspace = true }
hpos-config-core = { path = "../core" }
serde_json = { workspace = true }
