name: Deploy
on:
  push:
    branches:
      - master
jobs:
  gen-web:
    env:
      CF_API_TOKEN: ${{ secrets.cf_api_token }}
    runs-on: ubuntu-latest
    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - uses: cachix/cachix-action@v10
      with:
        name: holochain-ci
    - name: Prepare Nix environment
      run: nix-shell --command "echo Completed"
    - name: Run all tests
      run: nix-shell --run 'cd gen-web; npm install; MEMBRANE_PROOF_SERVICE_URL=https://membrane-proof-service.holo.host/ npm run build; wrangler publish'
